name: CI - Backtest (Smoke)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run CI backtest (deterministic)
        run: python models/backtest_ci.py

      - name: Smoke tests (only test_smoke.py)
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: python -m pytest -q tests/test_smoke.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: backtest-ci-report
          path: reports/backtest_ci_report.csv
          if-no-files-found: error
